# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 16:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_timelinepost'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepost',
            name='likes',
            field=models.ManyToManyField(related_name='liked_timeline_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timelinepost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
