# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160310_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelinepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='timelinepost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='TimelinePost',
        ),
    ]
